### ISSUE TITLE
Add a bsn! macro

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/i-cant-believe-its-not-bsn#3]
We should be able to generate the required bundle code from the BSN syntax proposed by cart in https://github.com/bevyengine/bevy/discussions/14437

**Comment by alice-i-cecile** [comment]
Cart's example:

```rust
fn player() -> impl Scene {
    bsn! {
        (
            Player {
                config: @"path_to_config.ron",
                team: Team::Blue,
            },
            Transform { translation { x: 10.0 } },
        )
    }
}
```

We can't easily do the cool @ syntax which relies on the `Construct` trait, but we should be able to get the field defaulting and nested braces for children going.

**Comment by NthTensor** [comment]
Do we consider this closed by https://github.com/Leafwing-Studios/i-cant-believe-its-not-bsn/pull/10?
